:PROPERTIES:
:ID:       d31224e1-4ef6-44f9-8350-4f890735f164
:END:
; -*- mode: org -*-
#+STARTUP: entitiespretty
#+language: ulang
#+DATE: {{{modification-time("%F %r", t)}}}
#+OPTIONS: org-html-head-include-default-style:t ^:nil _:nil email:t \n:nil Tex:t LaTeX:t broken-links:mark toc:t
#+HTML_DOCTYPE: html5
#+HTML_LINK_HOME: https://compiler.company
#+HTML_LINK_UP: https://compiler.company
#+LATEX_HEADER: \usepackage{placeins}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \PassOptionsToPackage{hyperref,x11names}{xcolor}
#+LATEX_HEADER: \usepackage{tocloft}
#+LATEX_HEADER: \usepackage[margin=2cm]{geometry}
#+COMMENT: #+ODT_STYLES_FILE: ~/org/ox/odt-theme.xml
#+LATEX_HEADER: \renewcommand{\cftsecleader}{\cftdotfill{\cftdotsep}}
#+LATEX_HEADER: \hypersetup{colorlinks, citecolor=red,filecolor=magenta,linkcolor=magenta,urlcolor=magenta}

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://cdn.compiler.company/font/commit-mono.css" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://cdn.compiler.company/font/3270.css" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://cdn.compiler.company/font/pragmata-pro.css" />

#+HTML_HEAD_EXTRA: <script type="text/javascript" src="https://cdn.compiler.company/js/jquery.min.js"></script>
#+HTML_HEAD_EXTRA: <script type="text/javascript" src="https://cdn.compiler.company/js/esquemadorg.js"></script>

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://cdn.compiler.company/css/htmlize.css" />
#+HTML_HEAD: <style type="text/css">
#+HTML_HEAD: body {
#+HTML_HEAD:     font-family:  "CommitMono", monospace;
#+HTML_HEAD:     -webkit-font-smoothing: antialiased;
#+HTML_HEAD:     -moz-osx-font-smoothing: grayscale;
#+HTML_HEAD:     font-feature-settings: "ss01", "ss03", "ss04", "ss05";
#+HTML_HEAD:     color:  #EFFAF9;
#+HTML_HEAD:     background-color: #0C0F0A;
#+HTML_HEAD: }

#+HTML_HEAD: div.status {
#+HTML_HEAD:     position: fixed;
# #+HTML_HEAD:     margin: 0.2em;
#+HTML_HEAD:     text-align: center;
#+HTML_HEAD: }

#+HTML_HEAD: h1, h2, h3, h4, h5, h6 {
#+HTML_HEAD:     position:  relative;
# #+HTML_HEAD:     margin:  16px 0 8px;
#+HTML_HEAD:     font-weight:  bold;
# #+HTML_HEAD:     line-height:  1.1;
#+HTML_HEAD:     color:  #DDCAD9;
#+HTML_HEAD:     text-rendering:  optimizeLegibility;
#+HTML_HEAD: }
#+HTML_HEAD: h1:before, h2:before, h3:before, h4:before, h5:before, h6:before {
#+HTML_HEAD:     position:  absolute;
#+HTML_HEAD:     top:  auto;
#+HTML_HEAD:     color:  #DDCAD9;
#+HTML_HEAD:     display:  none;
#+HTML_HEAD:     text-align: left;
#+HTML_HEAD: }
#+HTML_HEAD: h1:before {
#+HTML_HEAD:     content:  "";
#+HTML_HEAD:     left:  -1.25em;
#+HTML_HEAD: }
#+HTML_HEAD: h2:before {
#+HTML_HEAD:     content:  "*";
#+HTML_HEAD:     left:  -2em;
#+HTML_HEAD:     color: #DDCAD9;
#+HTML_HEAD: }
#+HTML_HEAD: h3:before {
#+HTML_HEAD:     content:  "**";
#+HTML_HEAD:     left:  -2em;
#+HTML_HEAD:     color: #DDCAD9;
#+HTML_HEAD: }
#+HTML_HEAD: h4:before {
#+HTML_HEAD:     content:  "***";
#+HTML_HEAD:     left:  -3em;
#+HTML_HEAD:     color: #DDCAD9;
#+HTML_HEAD: }
#+HTML_HEAD: h5:before {
#+HTML_HEAD:     content:  "****";
#+HTML_HEAD:     left:  -3em;
#+HTML_HEAD: }
#+HTML_HEAD: h6:before {
#+HTML_HEAD:     content:  "*****";
#+HTML_HEAD:     left:  -4em;
#+HTML_HEAD: }
#+HTML_HEAD: i, em, b, strong {
#+HTML_HEAD:     padding-left:  .1em;
#+HTML_HEAD:     padding-right:  .1em;
#+HTML_HEAD: }
#+HTML_HEAD: b, strong {
#+HTML_HEAD:     font-weight:  bold;
#+HTML_HEAD:     color:  #EDF060;
#+HTML_HEAD: }
#+HTML_HEAD: b:before, b: after, strong:before, strong: after {
#+HTML_HEAD:     content:  "*";
#+HTML_HEAD: }
#+HTML_HEAD: i:before, i: after, em:before, em: after {
#+HTML_HEAD:     content:  "/";
#+HTML_HEAD: }
#+HTML_HEAD: hr {
#+HTML_HEAD:     margin:  0;
#+HTML_HEAD:     border:  0;
#+HTML_HEAD: }
#+HTML_HEAD: hr: after {
#+HTML_HEAD:     display:  block;
#+HTML_HEAD:     margin:  20px 0;
#+HTML_HEAD:     content:  "----------------------------------------------------------------";
#+HTML_HEAD:     color:  #EDF060;
#+HTML_HEAD: }
#+HTML_HEAD: ul, ol {
#+HTML_HEAD:     padding:  0;
#+HTML_HEAD:     margin:  0 0 20px 20px;
#+HTML_HEAD: }
#+HTML_HEAD: code, pre {
#+HTML_HEAD:     font-family:  "3270", monospace;
#+HTML_HEAD:     overflow: overlay;
#+HTML_HEAD: }
#+HTML_HEAD: code {
#+HTML_HEAD:   font-family:  monospace;
#+HTML_HEAD:   color:  #EDF060;
#+HTML_HEAD:   background-color:  #303330;
#+HTML_HEAD: }
# #+HTML_HEAD: code:before, code:after {
# #+HTML_HEAD:     content:  "=";
# #+HTML_HEAD:     color:  #DDCAD9;
# #+HTML_HEAD: }
#+HTML_HEAD: .src {
#+HTML_HEAD:   font-family: monospace;
#+HTML_HEAD: }
#+HTML_HEAD: p::after{
#+HTML_HEAD:     content: "\a\a";
#+HTML_HEAD:     white-space: pre;
#+HTML_HEAD: }
#+HTML_HEAD: pre {
#+HTML_HEAD:     font-family:  monospace;
#+HTML_HEAD:     display:  block;
#+HTML_HEAD:     margin:  0 0 14px;
#+HTML_HEAD:     padding:  15px;
#+HTML_HEAD:     border-radius:  3px 3px 3px 3px;
#+HTML_HEAD:     background-color:  #303030;
# #+HTML_HEAD:     word-break:  break-all;
# #+HTML_HEAD:     word-wrap:  break-word;
#+HTML_HEAD: }
#+HTML_HEAD: 
#+HTML_HEAD: blockquote {
#+HTML_HEAD:     padding:  0 0 0 20px;
#+HTML_HEAD:     margin:  0 30px 20px -22.5px;
#+HTML_HEAD:     color:  #AAD3F8;
#+HTML_HEAD:     border-left:  8px solid #B08889;
#+HTML_HEAD: }

#+HTML_HEAD: pre.example {
#+HTML_HEAD:     border-left:  8px solid #493657;
#+HTML_HEAD: }

#+HTML_HEAD: blockquote p: last-child {
#+HTML_HEAD:     margin-bottom:  0;
#+HTML_HEAD: }
#+HTML_HEAD: img {
#+HTML_HEAD:     display:  block;
#+HTML_HEAD:     max-width: 100%;
#+HTML_HEAD:     height: auto;
#+HTML_HEAD:     margin:  auto;
#+HTML_HEAD:     border-radius:  5px;
#+HTML_HEAD:     padding-bottom: 1em;
#+HTML_HEAD: }
#+HTML_HEAD: figure > object {
#+HTML_HEAD:   height: auto;
#+HTML_HEAD:   margin: auto;
#+HTML_HEAD: }
#+HTML_HEAD: a {
#+HTML_HEAD:     font-weight:  inherit;
#+HTML_HEAD:     line-height:  inherit;
#+HTML_HEAD:     color:  #84DCC6;
#+HTML_HEAD: }
#+HTML_HEAD: sup a:before {
#+HTML_HEAD:     content:  "[";
#+HTML_HEAD: }
#+HTML_HEAD: sup a:after {
#+HTML_HEAD:     content:  "]";
#+HTML_HEAD: }
#+HTML_HEAD: a:hover {
#+HTML_HEAD:     text-decorac: blink;
#+HTML_HEAD:     color: #C43952;
#+HTML_HEAD:     background-color: #222222;
#+HTML_HEAD: }
#+HTML_HEAD: table {
#+HTML_HEAD:     line-height:  1.8;
#+HTML_HEAD:     margin-bottom:  15px;
#+HTML_HEAD:     max-width:  100%;
#+HTML_HEAD:     width:  100%;
#+HTML_HEAD:     border: 1px solid lightsteelblue;
#+HTML_HEAD:     border-style: inset;
#+HTML_HEAD: }
#+HTML_HEAD: table td, table th {
#+HTML_HEAD:     padding:  0 15px;
#+HTML_HEAD: }
#+HTML_HEAD: table th.left, table td.left {
#+HTML_HEAD:     text-align:  left;
#+HTML_HEAD: }
#+HTML_HEAD: table th.right, table td.right {
#+HTML_HEAD:     text-align:  right;
#+HTML_HEAD: }
#+HTML_HEAD: td, th {
#+HTML_HEAD:   border: 1px solid lightsteelblue;
#+HTML_HEAD:   border-style: outset;
#+HTML_HEAD: }

#+HTML_HEAD: /* body */
#+HTML_HEAD: body {
#+HTML_HEAD:     margin:  auto auto;
# #+HTML_HEAD:     max-width:  98%;
#+HTML_HEAD: }
#+HTML_HEAD: /* head */
#+HTML_HEAD: .masthead {
#+HTML_HEAD:     color:  #EDF060;
#+HTML_HEAD: }
#+HTML_HEAD: .masthead: after {
#+HTML_HEAD:     display:  block;
#+HTML_HEAD:     content:  '----------------------------------------------------------------';
# #+HTML_HEAD:     margin:  10px 0;
#+HTML_HEAD:     color:  #EDF060;
#+HTML_HEAD: }
#+HTML_HEAD: .masthead a {
#+HTML_HEAD:     color:  #EDF060;
#+HTML_HEAD: }
#+HTML_HEAD: .masthead ul {
#+HTML_HEAD:     list-style:  none;
#+HTML_HEAD: }
#+HTML_HEAD: .masthead li {
#+HTML_HEAD:     display:  inline-block;
#+HTML_HEAD: }
#+HTML_HEAD: .masthead li + li:before {
#+HTML_HEAD:     display:  inline-block;
#+HTML_HEAD:     content:  "\00B7 \00a0";
#+HTML_HEAD:     color:  #EDF060;
#+HTML_HEAD: }
#+HTML_HEAD: /* searchform*/
#+HTML_HEAD: #searchform {
#+HTML_HEAD:     position:  absolute;
#+HTML_HEAD:     top:  54px;
#+HTML_HEAD:     right:  30.4%;
#+HTML_HEAD: }
#+HTML_HEAD: #searchform #s {
#+HTML_HEAD:     background:  url("/media/img/search.png") no-repeat 5px 6px;
#+HTML_HEAD:     box-shadow:  inset 0 1px 1px rgba(0,0,0,0.1);
#+HTML_HEAD:     border:  1px solid #ddd;
#+HTML_HEAD:     border-radius:  2px;
#+HTML_HEAD:     -moz-border-radius:  2px;
#+HTML_HEAD:     width:  90px;
#+HTML_HEAD:     height:  30px;
#+HTML_HEAD:     line-height:  12px;
#+HTML_HEAD:     padding:  4px 10px 4px 28px;
#+HTML_HEAD: 
#+HTML_HEAD:     -webkit-transition-duration:  400ms;
#+HTML_HEAD:     -webkit-transition-property:  width, background;
#+HTML_HEAD:     -webkit-transition-timing-function:  ease;
#+HTML_HEAD:     -moz-transition-duration:  400ms;
#+HTML_HEAD:     -moz-transition-property:  width, background;
#+HTML_HEAD:     -moz-transition-timing-function:  ease;
#+HTML_HEAD:     -o-transition-duration:  400ms;
#+HTML_HEAD:     -o-transition-property:  width, background;
#+HTML_HEAD:     -o-transition-timing-function:  ease;
#+HTML_HEAD: }
#+HTML_HEAD: #searchform #s: focus {
#+HTML_HEAD:     background-color:  #3F3F37;
#+HTML_HEAD:     width:  160px;
#+HTML_HEAD: }
#+HTML_HEAD: .masthead img.avatar {
#+HTML_HEAD:     position:  relative;
#+HTML_HEAD:     float:  right;
#+HTML_HEAD:     margin-top:  -100px;
#+HTML_HEAD:     margin-bottom:  -100%;
#+HTML_HEAD:     margin-right:  10%;
#+HTML_HEAD:     width:  200px;
#+HTML_HEAD:     background-color:  #3F3F37;
#+HTML_HEAD: }
#+HTML_HEAD: /* post */
#+HTML_HEAD: .post {
#+HTML_HEAD:     position:  relative;
#+HTML_HEAD: }
#+HTML_HEAD: .post: after {
#+HTML_HEAD:     display:  block;
#+HTML_HEAD:     content:  "----------------------------------------------------------------";
#+HTML_HEAD:     color:  #EDF060;
#+HTML_HEAD: }
#+HTML_HEAD: .post img {
#+HTML_HEAD:     max-width:  100%;
#+HTML_HEAD: }
#+HTML_HEAD: .post li {
#+HTML_HEAD:     list-style:  none outside none;
#+HTML_HEAD: }
#+HTML_HEAD: .post ul > li:before {
#+HTML_HEAD:     content:  "- ";
#+HTML_HEAD:     margin-left:  -1.25em;
#+HTML_HEAD:     color:  #EDF060;
#+HTML_HEAD: }
#+HTML_HEAD: .post ol {
#+HTML_HEAD:     counter-reset:  o-list;
#+HTML_HEAD: }
#+HTML_HEAD: .post ol > li:before {
#+HTML_HEAD:     content:  counter(o-list) ") ";
#+HTML_HEAD:     counter-increment:  o-list;
#+HTML_HEAD:     margin-left:  -1.85em;
#+HTML_HEAD:     color:  #EDF060;
#+HTML_HEAD: }
#+HTML_HEAD: 
#+HTML_HEAD: /* special for li in pre */
#+HTML_HEAD: .post pre li {
#+HTML_HEAD:     font-family:  monospace;
#+HTML_HEAD:     list-style-type:  decimal;
#+HTML_HEAD: }
#+HTML_HEAD: 
#+HTML_HEAD: .post pre li:before {
#+HTML_HEAD:     display:  none;
#+HTML_HEAD: }
#+HTML_HEAD: 
#+HTML_HEAD: /* meta info */
#+HTML_HEAD: .post-info {
#+HTML_HEAD:     display:  inline-block;
#+HTML_HEAD:     margin:  -10px 0 -10px;
#+HTML_HEAD:     color:  #EDF060;
#+HTML_HEAD: }
#+HTML_HEAD: .post-info + .post-info:before {
#+HTML_HEAD:     content:  "\2223 \00a0";
#+HTML_HEAD: }
#+HTML_HEAD: .post-meta: after {
#+HTML_HEAD:     content:  "----------------------------------------------------------------";
#+HTML_HEAD:     display:  block;
#+HTML_HEAD:     margin-top:  -1px;
#+HTML_HEAD:     color:  #EDF060;
#+HTML_HEAD: }
#+HTML_HEAD: 
#+HTML_HEAD: /* nav */
#+HTML_HEAD: div #nav {
#+HTML_HEAD:   z-index: 10;
#+HTML_HEAD:   top:  0.2em;
#+HTML_HEAD:   left: 0.2em;
#+HTML_HEAD:   text-align: left;
#+HTML_HEAD:   font-size: 1.2rem;
#+HTML_HEAD:   cursor: pointer;
#+HTML_HEAD:   position: fixed;
#+HTML_HEAD: }

#+HTML_HEAD: div #nav h2 {
#+HTML_HEAD:   margin: 0em;
#+HTML_HEAD: }

#+HTML_HEAD: #index {
#+HTML_HEAD:   display: block;
#+HTML_HEAD:   text-align: left;
#+HTML_HEAD:   color:  #DDCAD9;
#+HTML_HEAD:   font-size: 48px;
#+HTML_HEAD:   font-stretch: ultra-expanded;
#+HTML_HEAD: }

#+HTML_HEAD: div #text-index {
#+HTML_HEAD:   color:  #EDF060;
#+HTML_HEAD:   display:  none;
#+HTML_HEAD:   text-align:  left;
#+HTML_HEAD:   backdrop-filter: blur(6px);
#+HTML_HEAD: }
#+HTML_HEAD: #org-div-home-and-up {
#+HTML_HEAD:   display: inline-flex;
#+HTML_HEAD: }
#+HTML_HEAD: button {
#+HTML_HEAD:   border: none;
#+HTML_HEAD:   background-color: inherit;
#+HTML_HEAD:   color: silver;
#+HTML_HEAD:   font-size: 16px;
#+HTML_HEAD:   cursor: pointer;
#+HTML_HEAD: }
#+HTML_HEAD: button:hover {background: #3F3F37; color:#EDF060;}
#+HTML_HEAD: .show {text-decoration: overline; float:right;}
#+HTML_HEAD: .hide {text-decoration: underline; float:right; text-underline-offset:0.2em;}
#+HTML_HEAD: .home {text-decoration: overline; float:left; font-size:24px;}
# #+HTML_HEAD: /* table of content */
# #+HTML_HEAD: nav, #table-of-contents {
# #+HTML_HEAD:   cursor: pointer;
# #+HTML_HEAD:     position:  fixed;
# #+HTML_HEAD:     right:  0.2em;
# #+HTML_HEAD:     top:  0.2em;
# #+HTML_HEAD:     border: 1px solid #e1e1e8;
# #+HTML_HEAD:     -webkit-box-shadow:  0 0 1em #777777;
# #+HTML_HEAD:     -moz-box-shadow:  0 0 1em #777777;
# #+HTML_HEAD:     -webkit-border-bottom-left-radius:  5px;
# #+HTML_HEAD:     -moz-border-radius-bottomleft:  5px;
# #+HTML_HEAD:     text-align:  right;
# #+HTML_HEAD:     /* ensure doesn't flow off the screen when expanded */
# #+HTML_HEAD:     height:  auto;
# #+HTML_HEAD:     overflow-y: scroll;
# #+HTML_HEAD:     z-index:  11;
# #+HTML_HEAD: }
# #+HTML_HEAD: 
# #+HTML_HEAD: #table-of-contents h2 {
# #+HTML_HEAD:   margin: 0em;
# #+HTML_HEAD:   font-size: 48px;
# #+HTML_HEAD:   font-stretch: ultra-expanded;
# #+HTML_HEAD: }
#+HTML_HEAD: 
# #+HTML_HEAD: #table-of-contents ul {
# #+HTML_HEAD:   margin-left:  14pt;
# #+HTML_HEAD:   margin-bottom:  10pt;
# #+HTML_HEAD:   padding:  0
# #+HTML_HEAD: }
#+HTML_HEAD: 
# #+HTML_HEAD: #table-of-contents li {
# #+HTML_HEAD:     padding:  0;
# #+HTML_HEAD:     margin:  1px;
# #+HTML_HEAD:     list-style:  none;
# #+HTML_HEAD: }

# #+HTML_HEAD: #table-of-contents li a {
# #+HTML_HEAD:     font-size:  16px;
# #+HTML_HEAD: }
# #+HTML_HEAD: 
# #+HTML_HEAD: #table-of-contents #text-table-of-contents {
# #+HTML_HEAD:   backdrop-filter: blur(6px);
# #+HTML_HEAD:   display:  none;
# #+HTML_HEAD:   text-align:  left;
# #+HTML_HEAD:   padding-right: 0.1em;
# #+HTML_HEAD: }
# #+HTML_HEAD: 
# #+HTML_HEAD: #table-of-contents: hover #text-table-of-contents {
# #+HTML_HEAD:     display:  block;
# #+HTML_HEAD:     padding:  0.5em;
# #+HTML_HEAD:     margin-top:  -1.5em;
# #+HTML_HEAD: }
# #+HTML_HEAD: 
#+HTML_HEAD: /* footer */
#+HTML_HEAD: .footer {
#+HTML_HEAD:     margin:  80px 0 0;
#+HTML_HEAD:     text-align:  center;
#+HTML_HEAD:     font-size:  13px;
#+HTML_HEAD:     color:  #DDCAD9;
#+HTML_HEAD:     left:  0em;
#+HTML_HEAD:     bottom:  0em;
#+HTML_HEAD: }
#+HTML_HEAD: .footer > p {
#+HTML_HEAD:     margin:  0;
#+HTML_HEAD:     line-height:  1.5;
#+HTML_HEAD: }
#+HTML_HEAD: .footpara {
#+HTML_HEAD:     display:  inline;
#+HTML_HEAD: }
#+HTML_HEAD: 
#+HTML_HEAD: /* Responsive
#+HTML_HEAD:    -------------------------------------------------- */
#+HTML_HEAD: 
#+HTML_HEAD: @media (min-width:  768px) {
#+HTML_HEAD:     /* Increase body padding and font-sizes */
#+HTML_HEAD:     body {
#+HTML_HEAD:         padding: 2em;
#+HTML_HEAD:         max-width: 70%;
#+HTML_HEAD:     }
#+HTML_HEAD:     h1:before, h2:before, h3:before, h4:before, h5:before, h6:before {
#+HTML_HEAD:         display:  inline;
#+HTML_HEAD:     }
#+HTML_HEAD: }
#+HTML_HEAD: 

# custom
#+HTML_HEAD: .subtitle {
#+HTML_HEAD:   text-align: center;
#+HTML_HEAD:   color: red;
#+HTML_HEAD:   font-weight: bold;
#+HTML_HEAD:   font-size: 1.1em;
#+HTML_HEAD: }
#+HTML_HEAD: .tag::before {
#+HTML_HEAD:   content: ":";
#+HTML_HEAD: }
#+HTML_HEAD: .tag::after {
#+HTML_HEAD:   content: ":";
#+HTML_HEAD: }
#+HTML_HEAD: .tag {
#+HTML_HEAD:   float: right;
#+HTML_HEAD:   color: #8A7090;
#+HTML_HEAD: }
#+HTML_HEAD: h3 .tag {
#+HTML_HEAD:   right: 0px;
#+HTML_HEAD:   position: absolute;
#+HTML_HEAD:   color: lightpink;
#+HTML_HEAD: }
#+HTML_HEAD: .org-center {
#+HTML_HEAD:   text-align: center;
#+HTML_HEAD: }
#+HTML_HEAD:
#+HTML_HEAD: .outline-2, .outline-3, .outline-4, .outline-5 {
# #+HTML_HEAD:   padding-left: 1em;
#+HTML_HEAD: }

# #+HTML_HEAD: .outline-2 {
# #+HTML_HEAD:   padding-top: 1.8em;
# #+HTML_HEAD: }

#+HTML_HEAD: .org-dl {
#+HTML_HEAD:   
#+HTML_HEAD: }

#+HTML_HEAD: .org-dl dt {
#+HTML_HEAD:   font-weight: bold;
#+HTML_HEAD: }

#+HTML_HEAD: .org-dl dt::after {
#+HTML_HEAD:   content: " :: ";
#+HTML_HEAD: }

#+HTML_HEAD: .org-dl dd::before {
#+HTML_HEAD:   font-size: xx-large;
#+HTML_HEAD:   content: "  ↳ ";
#+HTML_HEAD: }

#+HTML_HEAD: .org-dl dd {
#+HTML_HEAD:   font-size: 0.9rem;
#+HTML_HEAD:   margin-bottom: 0.5em;
#+HTML_HEAD:   margin-left: 2em;
#+HTML_HEAD: }

#+HTML_HEAD: .title {
#+HTML_HEAD:   text-align: center;
# #+HTML_HEAD:   padding-top: 1.8em;
#+HTML_HEAD: }

#+HTML_HEAD: div#postamble.status {
#+HTML_HEAD:   text-align: left;
#+HTML_HEAD: }
#+HTML_HEAD: .org-org-ref-acronym {
#+HTML_HEAD:     /* org-ref-acronym-face */
#+HTML_HEAD:     color: #ee7600;
#+HTML_HEAD:     text-decoration: underline;
#+HTML_HEAD: }
#+HTML_HEAD: .org-org-ref-cite {
#+HTML_HEAD:     /* org-ref-cite-face */
#+HTML_HEAD:     color: #c3d5c3;
#+HTML_HEAD:     text-decoration: underline;
#+HTML_HEAD: }
#+HTML_HEAD: .org-org-ref-glossary {
#+HTML_HEAD:     /* org-ref-glossary-face */
#+HTML_HEAD:     color: #8968cd;
#+HTML_HEAD:     text-decoration: underline;
#+HTML_HEAD: }
#+HTML_HEAD: .org-org-ref-label {
#+HTML_HEAD:     /* org-ref-label-face */
#+HTML_HEAD:     color: #8b008b;
#+HTML_HEAD:     text-decoration: underline;
#+HTML_HEAD: }
#+HTML_HEAD: .org-org-ref-ref {
#+HTML_HEAD:     /* org-ref-ref-face */
#+HTML_HEAD:     color: #e1cc96;
#+HTML_HEAD:     text-decoration: underline;
#+HTML_HEAD: }
#+HTML_HEAD: .org-org-scheduled {
#+HTML_HEAD:     /* org-scheduled */
#+HTML_HEAD:     color: #006400;
#+HTML_HEAD: }
#+HTML_HEAD: .org-org-scheduled-previously {
#+HTML_HEAD:     /* org-scheduled-previously */
#+HTML_HEAD:     color: #b22222;
#+HTML_HEAD: }
#+HTML_HEAD: .org-org-scheduled-today {
#+HTML_HEAD:     /* org-scheduled-today */
#+HTML_HEAD:     color: #006400;
#+HTML_HEAD: }
#+HTML_HEAD: .org-org-sexp-date {
#+HTML_HEAD:     /* org-sexp-date */
#+HTML_HEAD:     color: #a020f0;
#+HTML_HEAD: }
#+HTML_HEAD: .org-org-special-keyword {
#+HTML_HEAD:     /* org-special-keyword */
#+HTML_HEAD:     color: #a020f0;
#+HTML_HEAD: }
#+HTML_HEAD: .org-org-todo {
#+HTML_HEAD:     /* org-todo */
#+HTML_HEAD:     color: #ff0000;
#+HTML_HEAD:     font-weight: bold;
#+HTML_HEAD: }
#+HTML_HEAD: .org-org-done {
#+HTML_HEAD:     /* org-done */
#+HTML_HEAD:     color: #85BB41;
#+HTML_HEAD:     font-weight: bold;
#+HTML_HEAD: }
#+HTML_HEAD: .PROJECT {
#+HTML_HEAD:     color: lightseagreen;
#+HTML_HEAD:     font-weight: bold;
#+HTML_HEAD: }
#+HTML_HEAD: .NOTE {
#+HTML_HEAD:     color: lemonchiffon;
#+HTML_HEAD:     font-weight: bold;
#+HTML_HEAD: }
#+HTML_HEAD: .PRODUCT {
#+HTML_HEAD:     color: olivedrab;
#+HTML_HEAD:     font-weight: bold;
#+HTML_HEAD: }
#+HTML_HEAD: .RELEASE {
#+HTML_HEAD:     color: maroon3;
#+HTML_HEAD:     font-weight: bold;
#+HTML_HEAD: }
#+HTML_HEAD: .NOTE {
#+HTML_HEAD:     color: lemonchiffon;
#+HTML_HEAD:     font-weight: bold;
#+HTML_HEAD: }
#+HTML_HEAD: .CODE {
#+HTML_HEAD:     color: bisque;
#+HTML_HEAD:     background-color: midnightblue;
#+HTML_HEAD:     font-weight: bold;
#+HTML_HEAD: }
#+HTML_HEAD: .HOLD {
#+HTML_HEAD:     color: red1;
#+HTML_HEAD:     font-weight: bold;
#+HTML_HEAD:     background-color: yellow1;
#+HTML_HEAD: }
#+HTML_HEAD: .WAIT {
#+HTML_HEAD:     color: red;
#+HTML_HEAD:     font-weight: bold;
#+HTML_HEAD:     background-color: yellow1;
#+HTML_HEAD: }
#+HTML_HEAD: .WIP {
#+HTML_HEAD:     color: darkorchid;
#+HTML_HEAD:     font-weight: bold;
#+HTML_HEAD: }
#+HTML_HEAD: .NOPE {
#+HTML_HEAD:     color: hotpink;
#+HTML_HEAD:     font-weight: bold;
#+HTML_HEAD:     background-color: darkgreen;
#+HTML_HEAD: }
#+HTML_HEAD: .RESEARCH {
#+HTML_HEAD:     color: maroon;
#+HTML_HEAD:     font-weight: bold;
#+HTML_HEAD: }
#+HTML_HEAD: .DONE {
#+HTML_HEAD:     color: green;
#+HTML_HEAD:     font-weight: bold;
#+HTML_HEAD: }
#+HTML_HEAD: .TODO {
#+HTML_HEAD:     color: red;
#+HTML_HEAD:     font-weight: bold;
#+HTML_HEAD: }
#+HTML_HEAD: .TEST {
#+HTML_HEAD:     color: orange;
#+HTML_HEAD:     font-weight: bold;
#+HTML_HEAD: }
#+HTML_HEAD: .TBD {
#+HTML_HEAD:     color: darkred;
#+HTML_HEAD:     font-weight: bold;
#+HTML_HEAD: }
#+HTML_HEAD: .HACK {
#+HTML_HEAD:     color: coral;
#+HTML_HEAD:     font-weight: bold;
#+HTML_HEAD: }
#+HTML_HEAD: .SPRINT {
#+HTML_HEAD:     color: violet;
#+HTML_HEAD:     font-weight: bold;
#+HTML_HEAD: }
#+HTML_HEAD: .org-org-upcoming-deadline {
#+HTML_HEAD:     /* org-upcoming-deadline */
#+HTML_HEAD:     color: #b22222;
#+HTML_HEAD: }
#+HTML_HEAD: .org-org-upcoming-distant-deadline {
#+HTML_HEAD:     /* org-upcoming-distant-deadline */
#+HTML_HEAD:     color: #000000;
#+HTML_HEAD:     background-color: #ffffff;
#+HTML_HEAD: }
#+HTML_HEAD: 
#+HTML_HEAD: .org-org-warning {
#+HTML_HEAD:     /* org-warning */
#+HTML_HEAD:     color: #ff0000;
#+HTML_HEAD:     font-weight: bold;
#+HTML_HEAD: }
#+HTML_HEAD: .status {
#+HTML_HEAD:   position: absolute;
#+HTML_HEAD:   left: 1em;
#+HTML_HEAD: }
#+HTML_HEAD: 
#+HTML_HEAD: div #footnotes {
#+HTML_HEAD:   padding-bottom: 1em;
#+HTML_HEAD: }
#+HTML_HEAD: 
#+HTML_HEAD:  </style>
#+HTML_HEAD:<script type="text/javascript">
# #+HTML_HEAD:  document.addEventListener('DOMContentLoaded',function() {
# #+HTML_HEAD:      document.getElementById("table-of-contents").onclick = function() {
# #+HTML_HEAD:          var elem = document.getElementById("text-table-of-contents");
# #+HTML_HEAD:          elem.style.display = elem.style.display == "block" ? "none" : "block";
# #+HTML_HEAD:      }
# #+HTML_HEAD:  });
# #+HTML_HEAD:  document.addEventListener('DOMContentLoaded',function() {
# #+HTML_HEAD:      document.getElementById("nav").onclick = function() {
# #+HTML_HEAD:          var elem = document.getElementById("text-index");
# #+HTML_HEAD:          elem.style.display = elem.style.display == "block" ? "none" : "block";
# #+HTML_HEAD:      }
# #+HTML_HEAD:  });
#+HTML_HEAD:
#+HTML_HEAD:  var url = document.location.href;
#+HTML_HEAD:  var orgsource = url.substring(0, url.lastIndexOf("."))+".org";
#+HTML_HEAD:  function show_org_source(){
#+HTML_HEAD:      document.location.href = orgsource;
#+HTML_HEAD:  }
#+HTML_HEAD:</script>
#+BEGIN_EXPORT latex
\newpage
#+END_EXPORT
